name: 'Deploy AWS EBS Application'
description: 'Deploys application package S3 and creates new application version in EBS'
author: 'Betterchalk'
inputs:
  ebs-app-name: 
    required: true
    description: 'EBS app name (e.g. myapp)'
  ebs-environment-name: 
    required: true
    description: 'EBS environment name (e.g. myapp-env)'
  s3-bucket: 
    required: true
    description: 'Name of S3 bucket to store app package (e.g. myapp-bucket)'
  s3-key: 
    required: true
    description: 'File name for app when stored in S3 (e.g. myapp-v0.1.0.zip)'
  aws-region: 
    required: true
    description: 'AWS region for the EBS app (e.g. us-east-2)'
  aws-platform: 
    required: true
    description: 'Platform the EBS app is based on (e.g. Docker)'
  aws-access-key-id: 
    required: true
    description: 'Access key for AWS user (e.g. ABC123DEF456)'
  aws-secret-access-key: 
    required: true
    description: 'Secret key for AWS user (e.g. 3xU9pK450o3QWeeJ87x)'
  file-path: 
    required: true
    description: 'The location of the bundled app file (e.g. ./myapp.zip)'
  version-label: 
    required: true
    description: 'Unique string to use as app version label (e.g. myapp-v0.1.0)'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - run: node ${{ github.action_path }}/dist/index.js
      shell: bash
