name: 'Deploy AWS EBS Application'
description: 'Github Action workflow to deploy apps using AWS S3 and ElasticBeanstalk'
author: 'Betterchalk'
branding:
  color: 'green'
  icon: 'refresh-cw'

inputs:
  ebs-app-name: 
    required: true
    description: 'EBS app name (e.g. myapp)'
  ebs-environment-name: 
    required: true
    description: 'EBS environment name (e.g. myapp-env)'
  s3-bucket: 
    required: true
    description: 'Name of S3 bucket to store app package (e.g. myapp-bucket)'
  s3-key: 
    required: true
    description: 'File name for app when stored in S3 (e.g. myapp-v0.1.0.zip)'
  aws-region: 
    required: true
    description: 'AWS region for the EBS app (e.g. us-east-2)'
  file-path: 
    required: true
    description: 'The location of the bundled app file (e.g. ./myapp.zip)'
  version-label: 
    required: true
    description: 'Unique string to use as app version label (e.g. myapp-v0.1.0)'
  aws-access-key-id: 
    required: true
    description: AWS access key credentials'
  aws-secret-access-key: 
    required: true
    description: 'AWS secret access key credentials'
  aws-session-token: 
    required: true
    description: 'AWS session key credentials'
  process-timeout: 
    required: false
    default: '300'
    description: 'Max duration to wait for AWS to pre-process and validate the environment 
    manifest (env.yaml) and configuration files (*.config files in the .ebextensions folder) 
    in the source bundle (if any). Value is in seconds (e.g. 300 - which means 5mins)'


runs:
  using: 'node20'
  main: 'dist/index.js'

